FROM node:20-alpine AS build
WORKDIR /myapp
COPY package*.json ./
RUN npm install
COPY . .

FROM node:20-alpine AS production
WORKDIR /myapp
COPY --from=build --chown=node:node /myapp ./
EXPOSE 3000
USER node
CMD ["npm", "start"]
